baseURL = "https://domyson.github.io"
languageCode = "zh-cn"
title = "满船清梦压星河"
theme = "github"
googleAnalytics = "G-V23G8H27BQ"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Treasure"
  description = "无关迟暮，不问翻覆."
  github = "domyson"
#   facebook = "MeiK2333"
#   twitter = "MeiK2333"1
#   linkedin = "MeiK2333"
#   instagram = "MeiK2333"
  #tumblr = "MeiK2333"
  email = "cnmlgbbg@hotmail.com"
  url = "https://domyson.github.io"
  keywords = "computer tech"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/avatar.png"
  location = "China"
  enableGitalk = true

   [params.gitalk]
     clientID = "d30dd7c2a5d15316e046" 
     clientSecret = "bf9a096b345b29028eaca439e2e0c70731b5fd1a" 
     repo = "domyson.github.io"
    owner = "domyson"
     admin = "domyson"
     id = "location.pathname"
    labels = "gitalk"
    perPage = 15
     pagerDirection = "last"
     createIssueManually = true
     distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/domyson"
#   [[params.links]]
#     title = "Link2"
#     href = "https://meik2333.com"
#     icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]