#website
baseURL = "https://DoMySon.github.io/"
#语言
languageCode = "zh-CN"
#默认语言
defaultContentLanguage = "zh-CN"
# 是否自动检测中文|英文字数
hasCJKLanguage = true
# 网站主题
title = "薛定谔的BUG"
#启动主题
theme = "maupassant"
# 保持分类名称 若为 false Getting Started` 这样的英文标签将会被转换为 `getting-started`
preserveTaxonomyNames = true

#每页文章数
paginate = 7
#分页URL显示
paginatePath = "page"

#是否关闭路径大小写转换
disablePathToLower = true


#启用 Emoji; see emoji-cheat-sheet.com
enableEmoji = false

#创建robots.txt，建议设置为true
enableRobotsTXT = true


# identifier必须唯一 weight越小越靠前
[[menu.main]]
  name = "文章"
  weight = 20
  identifier = "archives"
  url = "/archives/"
# [[menu.main]]
#   name = "标签"
#   weight = 30
#   identifier = "tags"
#   url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "工具"
  weight = 50
  identifier = "tools"
  url = "/tools/"


[params]
  #卜算子页面计数
  since = "2019"
  busuanzi = true
  subtitle = "专注于各种划水"
  author = "Treasure"
 

# URL样式
#将改变content/post/文件夹下所有文章的URL。
#/:monthname/:day/:weekday/:weekdayname/:yearday/:section/:title/:slug/:filename/:title/ 所有可用属性
[permalinks]
  post = "/:year/:month/:title/" #"/:section/:title" #

# 字数统计和预计时间
moreMeta = true

# 友情链接
[[params.links]]
  # title = "Android Gradle权威指南" #悬停提示
  # name = "Android Gradle权威指南" #页面显示
  # url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"

#广告栏配置
# [[params.ads]]
#   title = "领取￥1888阿里云产品通用代金券"
#   url = "https://promotion.aliyun.com/ntms/act/enterprise-discount.html?userCode=jdg9oj97"
#   img = "https://img.alicdn.com/tfs/TB1aDXhXpzqK1RjSZFvXXcB7VXa-259-194.jpg"

#disqusShortname = "Treasure"
#文章摘要长度
#summaryLength = 140 



# see https://utteranc.es
#pathname
#url
#title
#og:title
#issue-number
[params.utteranc]
  enable = true
  repo = "DoMySon/Treasure"    # 存储评论的Repo，格式为 owner/repo
  issueTerm = "title"  #表示你选择以那种方式让github issue的评论和你的文章关联。
  theme = "github-dark" # 样式主题，有github-light和github-dark两种


# 版权声明
# [params.cc]
#     name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
#     link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"